name: all_events
version: 1.0.0+1
publish_to: none
description: A project for AllEvents practical round
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter_staggered_grid_view: ^0.7.0
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  get_storage: ^2.1.1
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  google_sign_in: ^6.2.1
  firebase_core: ^2.31.0
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/

